### ISSUE TITLE
Serialization/Deserialization fails if infiinity is encountered

### ISSUE THREAD

**Issue by Lazrius** [prozolic/CsToml#28]
If a double (and likely others, I haven't checked) is set to infinity, it will successfully serialize, but the output cannot be deserialized.

Reproduction:

```cs
[TomlSerializedObject]
public partial class TestData
{
    [TomlValueOnSerialized] public string E { get; set; }
    [TomlValueOnSerialized] public int EE { get; set; }
    [TomlValueOnSerialized] public long EEE { get; set; }
    [TomlValueOnSerialized] public float EEEE { get; set; }
    [TomlValueOnSerialized] public double EEEEE { get; set; }
}

        var testData = new TestData
        {
            E = "E",
            EE = int.MaxValue,
            EEE = long.MaxValue,
            EEEE = float.MaxValue,
            EEEEE = double.PositiveInfinity,
        };

        var outToml = CsTomlSerializer.Serialize(testData);
        var newTestData = CsTomlSerializer.Deserialize<TestData>(outToml.ByteSpan); // Crash here
```

The output toml from Serialize looks like the following:
```toml
E = "E"
EE = 2147483647
EEE = 9223372036854775807
EEEE = 3.4028234663852886E+38
EEEEE = Infinity.0
Id = 3576540641
V2 = [ 123.0, 456.0]
```
